### ISSUE TITLE
Transition over?

### ISSUE THREAD

**Issue by effigies** [bids-standard/schema-docs#1]
@bendhouseart Can you make me a maintainer on https://readthedocs.org/projects/bidsschematools/?

And what do we need to do to transition that to use the base repository, and give up this one?

**Comment by bendhouseart** [comment]
Slack me your email for RTD and I'll add you.

Also, it's migrated as of today, so I'm going to archive the schemadocs repo.

**Comment by effigies** [comment]
Awesome. Thanks!
